import { YamlStore } from '../storage/yamlStore';
import { CATEGORY_META } from '../models/annotation';

export function generateMarkdown(store: YamlStore): string {
  const annotations = store.getAnnotations();
  const markers = store.getReviewMarkers();
  const criticalFlags = store.getCriticalFlags();
  const narrative = store.getNarrative();

  const lines: string[] = [];

  lines.push('## CodeDiary — Change Plan');
  lines.push('');

  // Narrative
  if (narrative) {
    lines.push('### Intent');
    lines.push('');
    lines.push(narrative);
    lines.push('');
  }

  // Stats
  const files = new Set(annotations.map(a => a.file));
  const reviewedFiles = new Set(markers.map(m => m.file));
  const totalReviewedLines = markers.reduce((sum, m) => sum + (m.line_end - m.line_start + 1), 0);
  const unreviewedCritical = criticalFlags.filter(f => !f.human_reviewed);

  lines.push('### Review Coverage');
  lines.push('');
  lines.push(`- **${annotations.length}** annotations across **${files.size}** files`);
  lines.push(`- **${reviewedFiles.size}** files with review markers (${totalReviewedLines} lines reviewed)`);
  if (criticalFlags.length > 0) {
    lines.push(`- **${criticalFlags.length - unreviewedCritical.length}/${criticalFlags.length}** critical regions reviewed`);
  }
  lines.push('');

  // Critical regions needing attention
  if (unreviewedCritical.length > 0) {
    lines.push('### ⚠ Unreviewed Critical Regions');
    lines.push('');
    for (const flag of unreviewedCritical) {
      lines.push(`- **${flag.file}** L${flag.line_start}-${flag.line_end} (${flag.severity})${flag.description ? ': ' + flag.description : ''}`);
    }
    lines.push('');
  }

  // Annotations grouped by file
  if (annotations.length > 0) {
    lines.push('### Annotations');
    lines.push('');

    const byFile = new Map<string, typeof annotations>();
    for (const ann of annotations) {
      if (!byFile.has(ann.file)) {
        byFile.set(ann.file, []);
      }
      byFile.get(ann.file)!.push(ann);
    }

    for (const [file, fileAnnotations] of byFile) {
      lines.push(`#### \`${file}\``);
      lines.push('');
      for (const ann of fileAnnotations) {
        const meta = CATEGORY_META[ann.category];
        lines.push(`- **${meta.label}** (L${ann.line_start}-${ann.line_end}): ${ann.text}`);
      }
      lines.push('');
    }
  }

  // Needs reviewer attention
  const needsReview = annotations.filter(a => a.category === 'needs_review' || a.category === 'confused');
  if (needsReview.length > 0) {
    lines.push('### Needs Reviewer Attention');
    lines.push('');
    for (const ann of needsReview) {
      const meta = CATEGORY_META[ann.category];
      lines.push(`- **${meta.label}** in \`${ann.file}\` L${ann.line_start}-${ann.line_end}: ${ann.text}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [CodeDiary](https://marketplace.visualstudio.com/items?itemName=codediary.codediary) — Reflect before you ship.*');

  return lines.join('\n');
}
