import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { __setWorkspaceFolder, __clearWorkspace, __setConfig } from '../__mocks__/vscode';
import { DiaryStore } from '../../src/storage/diaryStore';
import { generateMarkdown } from '../../src/export/markdownExport';
import { Annotation } from '../../src/models/annotation';
import { ReviewMarker } from '../../src/models/reviewMarker';
import { CriticalFlag } from '../../src/models/criticalFlag';

let tmpDir: string;

function makeAnnotation(overrides: Partial<Annotation> = {}): Annotation {
  return {
    id: 'ann-1',
    file: 'src/foo.ts',
    line_start: 10,
    line_end: 20,
    category: 'verified',
    text: 'Looks good',
    source: 'manual',
    created_at: '2026-01-01T00:00:00Z',
    ...overrides,
  };
}

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'codediary-export-'));
  fs.mkdirSync(path.join(tmpDir, '.vscode'), { recursive: true });
  __setWorkspaceFolder(tmpDir);
  __setConfig({
    'codediary.storagePath': '.vscode/codediary.yaml',
    'codediary.defaultScope': 'shared',
  });
});

afterEach(() => {
  __clearWorkspace();
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

describe('generateMarkdown', () => {
  it('generates header for empty store', () => {
    const store = new DiaryStore();
    const md = generateMarkdown(store);
    expect(md).toContain('## CodeDiary — Change Plan');
    expect(md).toContain('**0** annotations across **0** files');
    expect(md).toContain('Generated by [CodeDiary]');
    store.dispose();
  });

  it('includes narrative when set', () => {
    const store = new DiaryStore();
    store.setNarrative('Refactoring the auth middleware');
    const md = generateMarkdown(store);
    expect(md).toContain('### Intent');
    expect(md).toContain('Refactoring the auth middleware');
    store.dispose();
  });

  it('omits narrative section when not set', () => {
    const store = new DiaryStore();
    const md = generateMarkdown(store);
    expect(md).not.toContain('### Intent');
    store.dispose();
  });

  it('shows annotation count and file count', () => {
    const store = new DiaryStore();
    store.addAnnotation(makeAnnotation({ id: 'a1', file: 'src/foo.ts' }));
    store.addAnnotation(makeAnnotation({ id: 'a2', file: 'src/bar.ts' }));
    const md = generateMarkdown(store);
    expect(md).toContain('**2** annotations across **2** files');
    store.dispose();
  });

  it('shows review coverage stats', () => {
    const store = new DiaryStore();
    const marker: ReviewMarker = {
      file: 'src/foo.ts',
      line_start: 1,
      line_end: 50,
      reviewer: 'alice',
      reviewed_at: '2026-01-01T00:00:00Z',
    };
    store.addReviewMarker(marker);
    const md = generateMarkdown(store);
    expect(md).toContain('**1** files with review markers (50 lines reviewed)');
    store.dispose();
  });

  it('shows critical region stats', () => {
    const store = new DiaryStore();
    const reviewed: CriticalFlag = {
      file: 'src/foo.ts', line_start: 1, line_end: 10,
      severity: 'critical', human_reviewed: true,
    };
    const unreviewed: CriticalFlag = {
      file: 'src/foo.ts', line_start: 20, line_end: 30,
      severity: 'high', human_reviewed: false,
    };
    store.addCriticalFlag(reviewed);
    store.addCriticalFlag(unreviewed);
    const md = generateMarkdown(store);
    expect(md).toContain('**1/2** critical regions reviewed');
    store.dispose();
  });

  it('shows unreviewed critical regions section', () => {
    const store = new DiaryStore();
    const flag: CriticalFlag = {
      file: 'src/auth.ts', line_start: 5, line_end: 15,
      severity: 'critical', human_reviewed: false,
      description: 'Token validation bypass',
    };
    store.addCriticalFlag(flag);
    const md = generateMarkdown(store);
    expect(md).toContain('### ⚠ Unreviewed Critical Regions');
    expect(md).toContain('**src/auth.ts** L5-15 (critical): Token validation bypass');
    store.dispose();
  });

  it('shows unreviewed critical without description', () => {
    const store = new DiaryStore();
    const flag: CriticalFlag = {
      file: 'src/auth.ts', line_start: 5, line_end: 15,
      severity: 'high', human_reviewed: false,
    };
    store.addCriticalFlag(flag);
    const md = generateMarkdown(store);
    expect(md).toContain('**src/auth.ts** L5-15 (high)');
    expect(md).not.toContain('**src/auth.ts** L5-15 (high):');
    store.dispose();
  });

  it('omits unreviewed section when all critical are reviewed', () => {
    const store = new DiaryStore();
    store.addCriticalFlag({
      file: 'src/foo.ts', line_start: 1, line_end: 5,
      severity: 'medium', human_reviewed: true,
    });
    const md = generateMarkdown(store);
    expect(md).not.toContain('Unreviewed Critical Regions');
    store.dispose();
  });

  it('groups annotations by file', () => {
    const store = new DiaryStore();
    store.addAnnotation(makeAnnotation({ id: 'a1', file: 'src/foo.ts', category: 'verified', text: 'ok' }));
    store.addAnnotation(makeAnnotation({ id: 'a2', file: 'src/bar.ts', category: 'needs_review', text: 'check this' }));
    const md = generateMarkdown(store);
    expect(md).toContain('#### `src/foo.ts`');
    expect(md).toContain('#### `src/bar.ts`');
    expect(md).toContain('**Verified** (L10-20): ok');
    expect(md).toContain('**Needs Review** (L10-20): check this');
    store.dispose();
  });

  it('shows needs reviewer attention section', () => {
    const store = new DiaryStore();
    store.addAnnotation(makeAnnotation({ id: 'a1', category: 'needs_review', text: 'please check' }));
    store.addAnnotation(makeAnnotation({ id: 'a2', category: 'confused', text: 'what is this?' }));
    store.addAnnotation(makeAnnotation({ id: 'a3', category: 'verified', text: 'fine' }));
    const md = generateMarkdown(store);
    expect(md).toContain('### Needs Reviewer Attention');
    expect(md).toContain('please check');
    expect(md).toContain('what is this?');
    // verified should not be in this section
    const attentionSection = md.split('### Needs Reviewer Attention')[1];
    expect(attentionSection).not.toContain('fine');
    store.dispose();
  });

  it('omits needs reviewer attention section when not needed', () => {
    const store = new DiaryStore();
    store.addAnnotation(makeAnnotation({ category: 'verified' }));
    const md = generateMarkdown(store);
    expect(md).not.toContain('Needs Reviewer Attention');
    store.dispose();
  });

  it('omits critical stats line when no critical flags', () => {
    const store = new DiaryStore();
    store.addAnnotation(makeAnnotation());
    const md = generateMarkdown(store);
    expect(md).not.toContain('critical regions reviewed');
    store.dispose();
  });

  it('excludes ephemeral ai_prompt annotations from export', () => {
    const store = new DiaryStore();
    store.addAnnotation(makeAnnotation({ id: 'a1', category: 'verified', text: 'Looks good' }));
    store.addAnnotation(makeAnnotation({ id: 'a2', category: 'ai_prompt', text: 'Refactor this please' }));
    const md = generateMarkdown(store);
    expect(md).toContain('Looks good');
    expect(md).not.toContain('Refactor this please');
    expect(md).toContain('**1** annotations across **1** files');
    store.dispose();
  });

  it('excludes all ephemeral annotations even when mixed with regular ones', () => {
    const store = new DiaryStore();
    store.addAnnotation(makeAnnotation({ id: 'a1', file: 'src/foo.ts', category: 'needs_review', text: 'Check this' }));
    store.addAnnotation(makeAnnotation({ id: 'a2', file: 'src/foo.ts', category: 'ai_prompt', text: 'AI note' }));
    store.addAnnotation(makeAnnotation({ id: 'a3', file: 'src/bar.ts', category: 'ai_prompt', text: 'Another AI note' }));
    const md = generateMarkdown(store);
    expect(md).toContain('**1** annotations across **1** files');
    expect(md).not.toContain('AI note');
    store.dispose();
  });
});
